### ISSUE TITLE
Nearly Working on Ubuntu 14.04

### ISSUE THREAD

**Issue by Vincat** [JamshedVesuna/vim-markdown-preview#21]
Hi

Continuation from previous bug report.

I am trying to use the local markdown, but it just produces empty files, no content. Web browser opens etc, just a blank page.

If I use 
```
let vim_markdown_preview_github=1
```
 it then works.

```
call system('see /tmp/vim-markdown-preview.html &> /dev/null &')
```
Does nothing. With the github=1 option then it works.

System info:
markdown-2.6.5
Vim 7.4.52
Zsh shell

All requirements are met (as far as I know). I have got Python 2 and 3 on this comp, not sure if that confuses anything.

**Comment by JamshedVesuna** [comment]
What happens if you run the following:
```shell
markdown README.md  > /tmp/vim-markdown-preview.html
```

Is the contents of  /tmp/vim-markdown-preview.html empty? Also, it looks like you also have grip installed, is that correct?

**Comment by Vincat** [comment]
Hi
This is the command I used successfully.
```
markdown_py TMUX_Notes.md > /tmp/vim-markdown-preview.html
```
I tried it on one of my notes.

**Comment by Vincat** [comment]
Hello

Any ideas ?

**Comment by JamshedVesuna** [comment]
Apologies for the delay. From your command above, it looks like you are using `markdown_py` instead of `markdown` or `grip`. As of now, this plugin only [supports](https://github.com/JamshedVesuna/vim-markdown-preview/blob/master/plugin/vim-markdown-preview.vim#L94) `markdown` and `grip`, but I'd be happy to include markdown_py.

To check, are you using OS X or Linux?

**Comment by Vincat** [comment]
On my system ( Ubuntu 14.04) there is only `markdown_py` .  I have since installed Markdown2 using the `pip3` command, that has given me `markdown2` command as well. 

I also tried setting up an alias in bash, but that didn't work either. 
`alias markdown=markdown_py`

**Comment by JamshedVesuna** [comment]
It looks like the main issue is that you aren't using `markdown`. Your alias isn't present when vim generates the html file. As you said, when you use:

```vim
let vim_markdown_preview_github=1
```
Then it works, because you are using `grip`. Did you have any issues when using `grip`?

If you are still inclined to use markdown without the above flag, try installing `markdown` with `sudo apt-get install markdown`.

**Comment by Vincat** [comment]
BINGO

That works !

Thanks, with now so many different ways to install software these days it's hard to know which way is the right way.
