### ISSUE TITLE
Not working on ubuntu 16.04

### ISSUE THREAD

**Issue by keighrim** [JamshedVesuna/vim-markdown-preview#38]
First of all, I love this great plugin, and many thanks for all the work. 
I've been using it for a while on my ubuntu laptop, and last week, after I went up to the new 16.04 by clean install, I found the plugin started to act weird. 
Everytime I hit preview, it ends up with an error message, saying 

```
Error detected while processing function Vim_Markdown_Preview_Local:
line   10:
E484: Can't open file /tmp/vM3gtfz/1
Press ENTER or type command to continue
```

Correct me if I'm wrong: from what I understand, if I have `vim_markdown_preview_temp_file` option turned on, the plugin will generate `vim-markdown-preview.html ` in the temp directory, and then opens it. 
However, it only manages to generate the html, then fails to open the file. 
And the error message says that somehow it's trying to access `/tmp/vM3gtfz/1` (name changes every time) , which does not exist.
If I turn the option off, it successfully generates html file in the working directory and *successfully* open it on the browser, but I'm still get the same error message.

I have installed `grip` and `xdotool`. 
Here are the relevant part of my current vimrc
```vimscript
let vim_markdown_preview_browser='Google Chrome'
let vim_markdown_preview_hotkey='<leader>r'
let vim_markdown_preview_toggle=1
let vim_markdown_preview_github=1
let vim_markdown_preview_temp_file=0
```

**Comment by JamshedVesuna** [comment]
Looks like there are a few things going on here:

1. Most importantly, because you have  `vim_markdown_preview_toggle=1`, this plugin will put the rendered `.html` file in your _local_ directory (rather than `/tmp/`). This is needed to render images with relative paths. Thus, _nothing_ should be in `/tmp/`.
2. If the  `vim_markdown_preview_temp_file` option is set to `1`, this plugin _removes_ the `.html` file. Typically, this option is better left as the default (`0`), especially for debugging.

What happens if you remove the following lines from your `.vimrc`:
```
let vim_markdown_preview_toggle=1
let vim_markdown_preview_github=1
let vim_markdown_preview_temp_file=0
```
Does this error message persist? If possible, can you post your vim version? Have you also tried pulling from origin recently?

**Comment by keighrim** [comment]
So, turned out that it was `vim_markdown_preview_toggle` the error messages was coming from, as turning `vim_markdown_preview_toggle` off eliminated errors!
Now no more html files in the working directory. (I guess this would cause a problem with loading local images, but I can live with that.)
And I also turned off `vim_markdown_preview_temp_file` as you recommended. 

Everything seems to work fine.
Thank you for the quick help!

(Close this if you want.)

**Comment by dexpota** [comment]
This is still an issue. I fixed this by changing this line
https://github.com/JamshedVesuna/vim-markdown-preview/blob/9b3ec41fb6f0f49d9bb7ca81fa1c62a8a54b1214/plugin/vim-markdown-preview.vim#L132
There is a missing quotation
```vim
    let chrome_wid = system("xdotool search --name 'vim-markdown-preview.html - " . g:vim_markdown_preview_browser . "'")
```

**Comment by dexpota** [comment]
@JamshedVesuna I am tagging you just because I am not sure if you will receive a notification with this closed issue. Maybe I should open a new issue?

**Comment by dtamez** [comment]
@dexpota   Your fix worked for me.  Thx.
