### ISSUE TITLE
vim_markdown_preview_browser has no effect

### ISSUE THREAD

**Issue by jonashaag** [JamshedVesuna/vim-markdown-preview#41]
```vim
let vim_markdown_preview_browser='Safari'
```

Preview is still opened in Google Chrome (default browser)

**Comment by JamshedVesuna** [comment]
What operating system are you using?

**Comment by jonashaag** [comment]
OS X

**Comment by JamshedVesuna** [comment]
Is Safari your default web browser? If not, then this won't work. If so, can you provide me more details about your system and vim version?

This plugin assumes if you aren't using Google Chrome, then your default browser is the one you specify in `vim_markdown_preview_browser`. [See this](https://github.com/JamshedVesuna/vim-markdown-preview/blob/master/plugin/vim-markdown-preview.vim#L85).

I'm happy to accept a PR that fixes this issue 😄

**Comment by jonashaag** [comment]
Default browser is Google Chrome, but I'd like to use Safari for Markdown preview because it annoys me that the preview window is always opened in a new tab in the existing Google Chrome window rather than a new window entirely.

**Comment by JamshedVesuna** [comment]
As of now, you'd have to change your default browser to Safari in order for VMP to work as you describe. This is because it's tricky to open a specific browser and refresh a specific page in the background on the cli (this would require browser specific commands, rather than simply [`open`ing](https://github.com/JamshedVesuna/vim-markdown-preview/blob/master/plugin/vim-markdown-preview.vim#L85) the html file).

I'm more than happy to accept a PR that has browser specific functionality!

> always opened in a new tab

This sounds like a bug. If you set your default browser to Google Chrome (and remove the `vim_markdown_preview_browser` you set), currently [an AppleScript](https://github.com/JamshedVesuna/vim-markdown-preview/blob/master/plugin/vim-markdown-preview.vim#L82) finds the tab that has the markdown preview and refreshes that. Can you provide more details about your system, browser, and Vim version?

**Comment by jonashaag** [comment]
No, what I want is that this plugin opens a new window for preview and does not use the window where I have all my usual tabs going on, because I always browse in full screen but want the preview to be non full screen.

**Comment by JamshedVesuna** [comment]
If you'd like, you can modify the [AppleScript](https://github.com/JamshedVesuna/vim-markdown-preview/tree/master/plugin/applescript) to open a new window and refresh that. Unfortunately, this sounds like a specific use case, so it won't be supported unless you make a PR with a flag to support this. Closing this out for now, but feel free to reopen.
